Write-Host "1) 编译项目"
Write-Host "mvn test"
Write-Host ""
Write-Host "2) 运行总览"
Write-Host "mvn -q -DskipTests exec:java -Dexec.mainClass=com.example.jvmstabilitydemo.JvmStabilityInterviewApplication"
Write-Host ""
Write-Host "3) 运行 OOM 示例（小堆）"
Write-Host "java -Xms128m -Xmx128m -cp target/classes com.example.jvmstabilitydemo.oom.OomLeakDemo --run"
Write-Host ""
Write-Host "4) 运行 Full GC 示例（打开 GC 日志）"
Write-Host "java -Xms256m -Xmx256m -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:gc.log -cp target/classes com.example.jvmstabilitydemo.fullgc.FullGcPressureDemo --run"
Write-Host ""
Write-Host "5) 运行死锁示例"
Write-Host "java -cp target/classes com.example.jvmstabilitydemo.deadlock.DeadlockDemo"
Write-Host ""
Write-Host "6) 运行线程定位示例"
Write-Host "java -cp target/classes com.example.jvmstabilitydemo.thread.ThreadTroubleshootingDemo --run"
